### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Abhipray04** [njacquelin/sports_field_registration#4]
How did you annotate your dataset? What tool did you use? Can you please go through the process of annotating a custom dataset?

Any leads will be appreciated. Cheers.

**Comment by Abhipray04** [comment]
Just following up on this question.

**Comment by njacquelin** [comment]
Hi,
I developped a small tool specifically for that, although I can't find it anymore.
Sorry I couldn't help with that.
